import type { User, Task } from "./types";

export const users: User[] = [
  { id: "user-1", name: "Alice", avatar: "user-avatar-1", role: "Requester" },
  { id: "user-2", name: "Bob", avatar: "user-avatar-2", role: "Helper" },
  { id: "user-3", name: "Charlie", avatar: "user-avatar-3", role: "Helper" },
  { id: "user-4", name: "Diana", avatar: "user-avatar-4", role: "Requester" },
  { id: "user-5", name: "Ethan", avatar: "user-avatar-5", role: "Helper" },
  { id: "user-6", name: "Fiona", avatar: "user-avatar-6", role: "Helper" },
];

export const tasks: Task[] = [
  {
    id: "task-1",
    title: "Backyard Gardening and Weeding",
    description: "I need help with general gardening tasks in my backyard. This includes weeding the flower beds, trimming some bushes, and planting new flowers. All tools will be provided. Should take about 3-4 hours.",
    category: "Gardening",
    location: "Greenwood, Seattle",
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 1500,
    workers: 1,
    requester: users[0],
    applicants: [users[1], users[2]],
    image: "task-gardening",
    urgency: "Flexible",
    distance: 3.5,
  },
  {
    id: "task-2",
    title: "Help Moving Apartments",
    description: "Looking for two strong individuals to help me move from a 2nd-floor apartment to a new one about 10 minutes away. The main items are a couch, a queen-sized bed, a dresser, and about 20 boxes. No truck needed, I have a U-Haul rented.",
    category: "Moving",
    location: "Capitol Hill, Seattle",
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 5000,
    workers: 2,
    requester: users[3],
    applicants: [users[4]],
    image: "task-moving",
    urgency: "Flexible",
    distance: 8.2,
  },
  {
    id: "task-3",
    title: "Deep Clean Before Move-out",
    description: "My lease is ending and I need a thorough deep clean of my 1-bedroom apartment. This includes kitchen (oven, fridge), bathroom, windows, and floors. Cleaning supplies can be provided if needed. Expect it to take a full day.",
    category: "Cleaning",
    location: "Bellevue, WA",
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 8000,
    workers: 1,
    requester: users[0],
    applicants: [],
    image: "task-cleaning",
    urgency: "Same Day",
    distance: 12.0,
  },
  {
    id: "task-4",
    title: "Leaking Tap Repair",
    description: "My kitchen sink has a persistent drip and I can't seem to fix it. Need a plumber to take a look and repair it as soon as possible. It's becoming very annoying!",
    category: "Plumbing",
    location: "Queen Anne, Seattle",
    date: new Date().toISOString(),
    budget: 2500,
    workers: 1,
    requester: users[3],
    applicants: [users[1], users[4], users[5]],
    image: "task-dogwalking",
    urgency: "Emergency",
    distance: 2.5,
  },
    {
    id: "task-5",
    title: "Paint Living Room Walls",
    description: "Need help painting my living room. The room is approximately 15x20 feet. I will provide the paint (a light beige color), brushes, rollers, and tape. Just need a skilled painter to ensure a clean and professional job.",
    category: "Home Improvement",
    location: "Fremont, Seattle",
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 4000,
    workers: 1,
    requester: users[0],
    applicants: [users[2]],
    image: "task-painting",
    urgency: "Flexible",
    distance: 5.1,
  },
];

export const analyticsData = {
    tasksCompleted: 132,
    totalEarnings: 21540,
    activeTasks: 5,
    avgRating: 4.8,
    tasksByCategory: [
        { name: 'Gardening', value: 45 },
        { name: 'Moving', value: 25 },
        { name: 'Cleaning', value: 30 },
        { name: 'Pets', value: 15 },
        { name: 'Home Improvement', value: 17 },
    ],
    earningsOverTime: [
        { date: 'Jan', earnings: 1200 },
        { date: 'Feb', earnings: 1800 },
        { date: 'Mar', earnings: 1500 },
        { date: 'Apr', earnings: 2200 },
        { date: 'May', earnings: 2500 },
        { date: 'Jun', earnings: 3100 },
    ]
}
